In [ ]:
#!pip install boto3

In [1]:
# Retrieve the list of existing buckets
import boto3
import logging

s3 = boto3.client('s3')
response = s3.list_buckets()

# Output the bucket names
print('Existing buckets:')
for bucket in response['Buckets']:
    print(f'  {bucket["Name"]}')

ModuleNotFoundError: No module named 'boto3'

In [7]:
from PIL import Image
  
# open method used to open different extension image file
url = 's3://lana-02/anitta.jpg'
url = 'https://lana-02.s3.us-east-2.amazonaws.com/anitta.jpg'
im = Image.open(url, 'r') 
  
# This method will show image in any image viewer 
im.show()

OSError: [Errno 22] Invalid argument: 'https://lana-02.s3.us-east-2.amazonaws.com/anitta.jpg'

In [6]:
import pandas as pd

url = 'https://lana-02.s3.us-east-2.amazonaws.com/aulas_BRAZIL_CITIES_REV2022.csv'

df = pd.read_csv(url)
print(len(df))
df.head()

5302

,CITY,STATE,CAPITAL,IBGE_RES_POP,IBGE_RES_POP_BRAS,IBGE_RES_POP_ESTR,IBGE_DU,IBGE_DU_URBAN,IBGE_DU_RURAL,IBGE_POP,...,Pu_Bank,Pr_Assets,Pu_Assets,Cars,Motorcycles,Wheeled_tractor,UBER,MAC,WAL-MART,POST_OFFICES
0,Abadia De Goiás,GO,0,6876,6876,0,2137,1546,591,5300,...,0,0,0,2158,1246,0,0,0,0,1
1,Abadia Dos Dourados,MG,0,6704,6704,0,2328,1481,847,4154,...,0,0,0,2227,1142,0,0,0,0,1
2,Abadiânia,GO,0,15757,15609,148,4655,3233,1422,10656,...,1,33724584,67091904,2838,1426,0,0,0,0,3
3,Abaetetuba,PA,0,141100,141040,60,31061,19057,12004,82956,...,4,76181384,800078483,5277,25661,0,0,0,0,2
4,Abaeté,MG,0,22690,22690,0,7694,6667,1027,18464,...,2,44974716,371922572,6928,2953,0,0,0,0,4

In [9]:
!pip install -q s3fs

WARNING: Ignoring invalid distribution -otocore (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -otocore (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -otocore (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -otocore (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -otocore (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -otocore (c:\programdata\anaconda3\lib\site-packages)

In [11]:
#!pip install -q s3fs
# lendo da URI do Amazon AWS - # timeout
import pandas as pd
import s3fs

uri = 's3://lana-02/aulas_BRAZIL_CITIES_REV2022.csv'

df = pd.read_csv(uri)
df.head()

,CITY,STATE,CAPITAL,IBGE_RES_POP,IBGE_RES_POP_BRAS,IBGE_RES_POP_ESTR,IBGE_DU,IBGE_DU_URBAN,IBGE_DU_RURAL,IBGE_POP,...,Pu_Bank,Pr_Assets,Pu_Assets,Cars,Motorcycles,Wheeled_tractor,UBER,MAC,WAL-MART,POST_OFFICES
0,Abadia De Goiás,GO,0,6876,6876,0,2137,1546,591,5300,...,0,0,0,2158,1246,0,0,0,0,1
1,Abadia Dos Dourados,MG,0,6704,6704,0,2328,1481,847,4154,...,0,0,0,2227,1142,0,0,0,0,1
2,Abadiânia,GO,0,15757,15609,148,4655,3233,1422,10656,...,1,33724584,67091904,2838,1426,0,0,0,0,3
3,Abaetetuba,PA,0,141100,141040,60,31061,19057,12004,82956,...,4,76181384,800078483,5277,25661,0,0,0,0,2
4,Abaeté,MG,0,22690,22690,0,7694,6667,1027,18464,...,2,44974716,371922572,6928,2953,0,0,0,0,4